name=easyJoystick
version=1.0.0
author=Naman Malhotra
maintainer= namanmalhotra451@gmail.com
sentence=A simple joystick library for Arduino.
paragraph=Supports deadzone, axis swapping, debounced button, percentage output, and 8-direction detection.
category=Input
url=https://github.com/Naman1177/easyJoystick
architectures=* Any Bit ADC Channel